// <auto-generated />
namespace ThirdNote.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class note_name_base64 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(note_name_base64));
        
        string IMigrationMetadata.Id
        {
            get { return "202209111202460_note_name_base64"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
