// <auto-generated />
namespace ThirdNote.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class tagLabel_fa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tagLabel_fa));
        
        string IMigrationMetadata.Id
        {
            get { return "202201031127184_tagLabel_fa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
