//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThirdNote.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meta
    {
        public int Id { get; set; }
        public bool Hidden { get; set; }
        public bool Markdown { get; set; }
        public bool Pin { get; set; }
        public bool Actionable { get; set; }
    
        public virtual Note Notes { get; set; }
    }
}
