//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThirdNote.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public Tag()
        {
            this.Notes = new HashSet<Note>();
        }
    
        public int Id { get; set; }
        public string Label { get; set; }
    
        public virtual ICollection<Note> Notes { get; set; }
    }
}
